<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\HappyGemini.Extensibility\HappyGemini.Extensibility.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="happygemini.plugin.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<Target Name="StageTestPlugin"
			AfterTargets="Build"
			Condition="'$(Configuration)' == 'Debug'">

		<PropertyGroup>
			<PluginStageDirectory>$(MSBuildProjectDirectory)\..\HappyGemini\bin\$(Configuration)\$(TargetFramework)\plugins\HappyGemini.TestPlugin</PluginStageDirectory>
		</PropertyGroup>

		<ItemGroup>
			<PluginOutputFiles Include="$(TargetDir)*" />
		</ItemGroup>

		<MakeDir Directories="$(PluginStageDirectory)" />

		<Copy SourceFiles="@(PluginOutputFiles)"
			  DestinationFolder="$(PluginStageDirectory)"
			  SkipUnchangedFiles="true" />

	</Target>

</Project>
