<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HappyGemini-9568ee0c-451f-4dd0-be1f-089f964783ca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JoyfulReaperLib.TcpServer" Version="0.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HappyGemini.Extensibility\HappyGemini.Extensibility.csproj" />
  </ItemGroup>
</Project>
